SELECT * FROM TALUNO;


ALTER TABLE TALUNO
ADD ESTADO CHAR(2) DEFAULT 'RS';


ALTER TABLE TALUNO
ADD SALARIO NUMBER(8,2) DEFAULT 620;

ALTER TABLE TALUNO
DROP COLUMN SALARIO;



UPDATE TALUNO
SET ESTADO = 'AC', SALARIO = 250
WHERE COD_ALUNO = 1;

UPDATE TALUNO
SET ESTADO = 'MT', SALARIO = 2000
WHERE COD_ALUNO = 2;

UPDATE TALUNO
SET ESTADO = 'SP', SALARIO = 800
WHERE COD_ALUNO = 4;

COMMIT;

SELECT * FROM TALUNO
WHERE ESTADO != 'RS' AND
SALARIO <= 800
ORDER BY SALARIO DESC;


INSERT INTO TALUNO (COD_ALUNO, NOME, CIDADE) VALUES(SEQ_ALUNO.NEXTVAL, 'VALDO', 'DOIS IRMAOS');
INSERT INTO TALUNO (COD_ALUNO, NOME, CIDADE) VALUES(SEQ_ALUNO.NEXTVAL, 'ALDO', 'QUATRO IRMAOS');

UPDATE TALUNO SET
ESTADO = 'SP',
SALARIO = 900,
NOME = 'PEDRO'
WHERE COD_ALUNO = 25;


SELECT ESTADO, SALARIO, NOME FROM TALUNO
ORDER BY ESTADO, SALARIO DESC;


ALTER TABLE  TALUNO
ADD NASCIMENTO DATE DEFAULT SYSDATE - 1000;--DIAS


SELECT SYSDATE FROM DUAL;


UPDATE TALUNO SET
NASCIMENTO = '12-10-2011'
where COD_ALUNO = 1;

UPDATE TALUNO SET
NASCIMENTO = '10/08/200'
WHERE COD_ALUNO = 2;

select * from TALUNO
WHERE NASCIMENTO BETWEEN TO_DATE ('25/05/2011', 'DD/MM/YYYY')
    AND TO_DATE('26/05/2015', 'DD/MM/YYYY');


SELECT * FROM TCONTRATO;

UPDATE TCONTRATO SET
DESCONTO = 5
WHERE COD_CONTRATO = 3;

SELECT * FROM TCONTRATO
WHERE DESCONTO IS NOT NULL;

SELECT COD_CONTRATO, TOTAL, DESCONTO FROM TCONTRATO
WHERE NVL(DESCONTO,0) BETWEEN 0 AND 10
ORDER BY DESCONTO;


SELECT * FROM TITEM
WHERE COD_CURSO IN (1,2,3);

select * from taluno
where cidade like '%A%';

COMMIT;

SELECT * FROM TCURSO;
ALTER TABLE TCURSO ADD PRE_REQ INTEGER;

UPDATE TCURSO SET
PRE_REQ = 1
WHERE COD_CURSO = 2;

SELECT * FROM TCURSO
WHERE PRE_REQ IS NOT NULL;
SELECT * FROM TCURSO
WHERE PRE_REQ IS NULL;

